systemart/apps/sysart/urls.py
from django.contrib import admin
from django.urls import path, include
from apps.main import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include("django.contrib.auth.urls")),
    path('accounts/register/', views.RegisterView.as_view(), name='register'),
    path('logout/', views.user_logout, name='logout'),

    path('analytics/', views.generate_report, name='analytics'),

    path('projects/', views.projects_view, name='projects'),
    path('projects/new/', views.ProjectView.as_view()),
    path('projects/delete/<int:project_id>/', views.delete_project, name='delete_project'),
    path('projects/<int:pk>/edit/', views.edit_project.as_view(), name='edit_project'),

    path('testcases/', views.testcase_view, name='testcases'),
    path('testcases/new/', views.TestCaseView.as_view()),
    path('testcases/order_by/<str:order_by>/', views.testcase_order_view, name='testcase_order'),
    path('testcases/delete/<int:testcase_id>/', views.delete_testcase, name='delete_testcase'),
    path('testcases/<int:pk>/edit/', views.edit_testcase.as_view(), name='edit_testcase'),

    path('testsets/', views.testset_view, name='testsets'),
    path('testsets/new/', views.TestSetView.as_view()),
    path('testsets/delete/<int:testset_id>/', views.delete_testset, name='delete_testset'),
    path('testsets/<int:pk>/edit/', views.edit_testset.as_view(), name='edit_testset'),
    path('testsets/<int:testset_id>/', views.desc_testset, name='desc_testset'),
    path('testsets/<int:testset_id>/order_by/<str:order_by>/', views.testset_order_view, name='testset_order'),
    path('testsets/delete/<int:testset_id>/<int:testcase_id>/', views.delete_testset_testcase, name='delete_testset_testcase'),

    path('testsets/<int:testset_id>/testcase/add/', views.add_testcase, name='add_testcase'),
    path('testsets/<int:testset_id>/testcase/add/order_by/<str:order_by>/', views.testcase_add_order_view, name='add_testcase_order'),
    path('testsets/testcase/<int:pk>/edit/', views.edit_testcase_desc.as_view(), name='edit_testcase'),

    path('bugreports/', views.bugreport_view, name='bugreports'),
    path('bugreports/new/', views.BugReportsView.as_view()),
    path('bugreports/order_by/<str:order_by>/', views.bugreport_order_view, name='bugreport_order'),
    path('bugreports/delete/<int:bug_id>/', views.delete_bugreport, name='delete_bugreport'),
    path('bugreports/<int:pk>/edit/', views.edit_bugreport.as_view(), name='edit_bugreport'),
    
    path('', views.index_view),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler403 = views.custom_permission_denied

systemart/apps/main/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from datetime import datetime
import uuid

# создание списка уровней приоритета
HIGH = "Высокий"
MIDDLE = "Средний"
LOW = "Низкий"
PRIORITY_CHOICES = {
    HIGH: "Высокий", 
    MIDDLE: "Средний",
    LOW: "Низкий",
}

class Projects(models.Model):
    """ Модель, описывающая проекты """
    
    project_id = models.AutoField(primary_key=True)
    project_name = models.CharField(max_length=128)
    description = models.TextField(max_length=120, null=True, blank=True)

    def __str__(self):
        return self.project_name


class Tester(AbstractUser):
    """ Модель, описывающая пользователя """

    # создание списка ролей для проектов
    SENIOR = "Главный тестировщик" # главный тестировщик
    DEFAULT = "Тестировщик"  # обычный тестировщик, стандартная роль
    PROJECT_ROLES_CHOICES = {
        SENIOR: "Главный тестировщик",
        DEFAULT: "Тестировщик"
    }

    role = models.CharField(
        max_length=25, 
        choices=PROJECT_ROLES_CHOICES, 
        default=DEFAULT
    )


class TestCases(models.Model):
    """ Модель, описывающая тест-кейсы """

    # создание списка типов кейсов
    POSITIVE = "Позитивный"
    NEGATIVE = "Негативный"
    CASE_TYPE_CHOICES = {
        POSITIVE: "Позитивный",
        NEGATIVE: "Негативный"
    }

    # создание списка статусов кейсов
    SUCCESS = "Успешно"
    FAIL = "Провален"
    SKIP = "Пропущен"
    NPASS = "Не пройден"
    CASE_STATUS_CHOICES = {
        SUCCESS: "Успешно",
        FAIL: "Провален",
        SKIP: "Пропущен",
        NPASS: "Не пройден"
    }

    name = models.CharField(max_length=128)

    case_type = models.CharField(
        max_length=10,
        choices=CASE_TYPE_CHOICES,
        default=POSITIVE
    )

    priority = models.CharField(
        max_length=10, 
        choices=PRIORITY_CHOICES, 
        default=LOW
    )

    case_status = models.CharField(
        max_length=10,
        choices=CASE_STATUS_CHOICES,
        default=NPASS,
        null=True, 
        blank=True
    )
    
    testcase_id = models.AutoField(primary_key=True)
    id = models.ForeignKey(Tester, on_delete=models.CASCADE, blank=True, editable=False)
    project = models.ForeignKey(Projects, on_delete=models.CASCADE)
    creation_date = models.DateTimeField(default=datetime.now, editable=False)
    precondition = models.TextField(max_length=120)
    runtime = models.DateTimeField(default=datetime.now, blank=True, null=True)
    case_file = models.FileField(upload_to='testcases/', null=True, blank=True)

    def save(self, *args, **kwargs):
        if self.pk and TestCases.objects.get(pk=self.pk).case_status != self.case_status:
            self.runtime = datetime.now()
        elif not self.pk:
            self.runtime = None
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name

class CaseSteps(models.Model):
    """ Модель, описывающая шаги кейса """

    step_id = models.AutoField(primary_key=True)
    testcase_id = models.ForeignKey(TestCases, on_delete=models.CASCADE)
    step = models.TextField(null=True, blank=True, max_length=512)
    predictedresult = models.TextField(null=True, blank=True, max_length=512)

class TestSet(models.Model):
    """ Модель, описывающая тестовые наборы """
    testset_id = models.AutoField(primary_key=True)
    testset_name = models.CharField(max_length=128)
    testcases = models.ManyToManyField(TestCases, blank=True)
    id = models.ForeignKey(Tester, on_delete=models.CASCADE, blank=True, editable=False)


class BugReports(models.Model):
    """ Модель, описывающая баг репорты """

    # создание списка статусов баг репортов
    OPEN = "Открыт"
    CLOSED = "Закрыт"
    INPROCESS = "В работе"
    BUG_STATUS_CHOICES = {
        OPEN: "Открыт",
        CLOSED: "Закрыт",
        INPROCESS: "В работе"
    }

    name = models.CharField(max_length=128)

    status = models.CharField(
        max_length=10,
        choices=BUG_STATUS_CHOICES,
        default=OPEN
    )

    priority = models.CharField(
        max_length=10, 
        choices=PRIORITY_CHOICES, 
        default=LOW
    )

    bug_id = models.AutoField(primary_key=True)
    testcase = models.ManyToManyField(TestCases)
    project = models.ForeignKey(Projects, on_delete=models.CASCADE)
    creation_date = models.DateTimeField(default=datetime.now, editable=False)
    id = models.ForeignKey(Tester, on_delete=models.CASCADE, blank=True, editable=False)
    description = models.TextField(max_length=512, null=True, blank=True)
    bug_file = models.FileField(upload_to='bug_reports/', null=True, blank=True)

    def __str__(self):
            return self.name

systemart/apps/main/views.py
from .forms import RegisterForm, ProjectForm, TestCaseForm, TestsetForm, ReportForm, FilterForm, CaseStepForm
from .models import Projects, TestCases, TestSet, BugReports
from django.http import Http404, JsonResponse, HttpResponse
from django.contrib.auth.mixins import PermissionRequiredMixin, LoginRequiredMixin
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.models import Group
from django.contrib.auth import logout
from django.contrib.auth import authenticate
from django.shortcuts import render, redirect
from django.views.generic.edit import FormView
from django.views.defaults import page_not_found, server_error, permission_denied
from django.views.generic.edit import UpdateView
from django.urls import reverse_lazy
from reportlab.lib.pagesizes import letter, landscape
from reportlab.platypus import Table, TableStyle
from reportlab.lib import colors
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.pdfgen import canvas
from datetime import datetime
from reportlab.lib.units import mm

pdfmetrics.registerFont(TTFont('Arial', 'arial.ttf'))

def custom_permission_denied(request, exception=None):
    return render(request, 'main/forbidden.html', status=403)

permission_denied = custom_permission_denied

# auth views
@login_required
def index_view(request):
    projects = Projects.objects.all()
    return render(request, 'main/index.html', {'projects': projects})

@login_required
def user_logout(request):
    if request.method == 'POST':
        logout(request)
        return redirect('login')
    return render(request, 'registration/logout.html')


from reportlab.lib.pagesizes import letter, landscape
from reportlab.lib import colors
from reportlab.platypus import Table, TableStyle, Paragraph
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.styles import ParagraphStyle

def generate_pdf(data, report_type):
    date = datetime.now().strftime("%B-%Y-%d")
    name = report_type + "-" + date

    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = f'attachment; filename="{name}.pdf"'

    c = canvas.Canvas(response, pagesize=landscape(letter))

    pdfmetrics.registerFont(TTFont('arial', '/usr/share/fonts/truetype/arial.ttf'))
    body_text_style = getSampleStyleSheet()['BodyText']
    new_body_text_style = ParagraphStyle(name='BodyText', parent=body_text_style, fontName='arial', fontSize=12)

    if report_type == 'testcases':
        headers = ['ID', 'Название', 'Приоритет', 'Статус', 'Тип кейса', 'Дата прохождения', 'Автор']
        table_data = [headers]
        for item in data:
            table_data.append([
                Paragraph(str(item.testcase_id), new_body_text_style),
                Paragraph(str(item.name), new_body_text_style),
                Paragraph(str(item.priority), new_body_text_style),
                Paragraph(str(item.case_status), new_body_text_style),
                Paragraph(str(item.case_type), new_body_text_style),
                Paragraph(str(item.runtime.strftime('%d-%m-%Y')), new_body_text_style),
                Paragraph(str(item.id), new_body_text_style),
            ])
    else:
        headers = ['ID', 'Название', 'Приоритет', 'Статус', 'Дата создания', 'Автор', 'Проект']
        table_data = [headers]
        for item in data:
            table_data.append([
                Paragraph(str(item.bug_id), new_body_text_style),
                Paragraph(str(item.name), new_body_text_style),
                Paragraph(str(item.priority), new_body_text_style),
                Paragraph(str(item.status), new_body_text_style),
                Paragraph(str(item.creation_date.strftime('%d-%m-%Y')), new_body_text_style),
                Paragraph(str(item.id), new_body_text_style),
                Paragraph(str(item.project), new_body_text_style),
            ])
    col_widths = [30, 150, 120, 120, 120, 120, 120]

    table = Table(table_data, colWidths=col_widths)

    body_style = TableStyle([
        ('FONT', (0, 0), (-1, -1), 'arial'),
        ('FONTSIZE', (0, 0), (-1, -1), 12),
    ])

    table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.grey),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('FONT', (0, 0), (-1, -1), 'arial'), 
        ('FONTSIZE', (0, 0), (-1, -1), 12),  
        ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
        ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
        ('GRID', (0, 0), (-1, -1), 1, colors.black)
    ]))

    table.setStyle(body_style)

    table_width = table.wrapOn(c, 0, 0)[0]
    page_width = letter[1]  
    x_coord = (page_width - table_width) / 2

    table_height = table.wrapOn(c, 0, 0)[1]
    page_height = letter[0]  
    y_coord = page_height - table_height - 30  
    if y_coord < 30:  
        y_coord = 30

    table.drawOn(c, x_coord, y_coord)

    c.save()
    return response



# objects views
@login_required
def generate_report(request):
    form = FilterForm(request.GET or None)
    if form.is_valid():
        start_date = form.cleaned_data['start_date']
        end_date = form.cleaned_data['end_date']
        report_type = form.cleaned_data['report_type']
        search_criteria = form.cleaned_data['search_criteria']
        start_runtime = form.cleaned_data['start_runtime']
        end_runtime = form.cleaned_data['end_runtime']

        if report_type == 'testcases':
            data = TestCases.objects.filter(runtime__range=(start_runtime, end_runtime), case_status=search_criteria)
        elif report_type == 'bugreports':
            data = BugReports.objects.filter(creation_date__range=(start_date, end_date))

        if 'download_pdf' in request.GET:
            return generate_pdf(data, report_type)
        else:
            context = {'form': form, 'data': data}
            return render(request, 'main/analytics.html', context)

    return render(request, 'main/analytics.html', {'form': form})

@login_required
def projects_view(request):
    projects = Projects.objects.all()
    return render(request, 'main/projects.html', {'projects': projects})

@login_required
def testcase_view(request):
    testcases = TestCases.objects.all()
    return render(request, 'main/testcases.html', {'testcases': testcases})

@login_required
def testcase_order_view(request, order_by):
    testcases = TestCases.objects.all()
    testcases = testcases.order_by(order_by)
    return render(request, 'main/testcases.html', {'testcases': testcases})

@login_required
def testset_view(request):
    testsets = TestSet.objects.all()
    return render(request, 'main/testsets.html', {'testsets': testsets})

@login_required
def testset_order_view(request, order_by, testset_id):
    testset = TestSet.objects.get(pk=testset_id)
    testcases = testset.testcases.order_by(order_by)
    return render(request, 'main/desc_testsets.html', {'testset': testset, 'testcases': testcases})

@login_required
def bugreport_view(request):
    bugreports = BugReports.objects.all()
    return render(request, 'main/bugreports.html', {'bugreports': bugreports})

@login_required
def bugreport_order_view(request, order_by):
    bugreports = BugReports.objects.all()
    bugreports = bugreports.order_by(order_by)
    return render(request, 'main/bugreports.html', {'bugreports': bugreports})

# create views
class ProjectView(LoginRequiredMixin, PermissionRequiredMixin, FormView):
    permission_required = 'project.create_project'
    login_url = '/accounts/login/'
    redirect_field_name = 'index'
    form_class = ProjectForm
    template_name = 'main/create_project.html'
    success_url = reverse_lazy('projects')

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)
 
class TestCaseView(LoginRequiredMixin, FormView):
    form_class = TestCaseForm
    template_name = 'main/create_testcase.html'
    success_url = reverse_lazy('testcases')
    login_url = '/accounts/login/'
    redirect_field_name = 'index'

    def form_valid(self, form):
        test_case = form.save(commit=False)
        if self.request.FILES:
            test_case.testcase_file = self.request.FILES['case_file']
        test_case.id = self.request.user
        test_case.save()
        formset = form.steps_formset(instance=test_case, data=self.request.POST, files=self.request.FILES)

        if formset.is_valid():
            print(self.request.POST)
            formset.save()
            return super().form_valid(form)
        else:
            context = self.get_context_data(form=form, steps_formset=formset)
            context['formset_errors'] = formset.errors

            return self.render_to_response(context)

    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        form = self.get_form()
        if self.request.method == 'POST':
            context['steps_formset'] = form.steps_formset(self.request.POST, self.request.FILES)
        else:
            context['steps_formset'] = form.steps_formset()
        return context
    
class TestSetView(LoginRequiredMixin, FormView):
    form_class = TestsetForm
    template_name = 'main/create_testset.html'
    success_url = reverse_lazy('testsets')
    login_url = '/accounts/login/'
    redirect_field_name = 'index'

    testcases = TestCases.objects.all()

    def form_valid(self, form):
        form.instance.id = self.request.user
        testset = form.save(commit=False)
        testset.save()
        form.save_m2m()
        return super().form_valid(form)

class BugReportsView(LoginRequiredMixin, FormView):
    form_class = ReportForm
    template_name = 'main/create_bugreport.html'
    success_url = reverse_lazy('bugreports')
    login_url = '/accounts/login/'
    redirect_field_name = 'index'

    def form_valid(self, form):
        form.instance.id = self.request.user
        form.save()

systemart/apps/main/templates/main/add_testcase.html
{% load static%}
<!DOCTYPE html>
<html>
<head>
    <title>Главная</title>
    <!-- css connecting -->
    <link rel="stylesheet" type="text/css" href="{% static "/css/main.css"%}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
</head>
<body>
{% block lists %}
<div>
<h1>Отметьте выбранные кейсы чекбоксами.</h1>
<form method="post">
    {% csrf_token %}
    <div>
        <table style="left:9%;"class="projectlist" border="0" cellpadding="8" cellspacing="3">
            <thead>
                <td> </td>
                <td style="width: 80px;">ID</td>
                <td style="width: 200px;">Название</td>
                <td style="width: 80px;">Приоритет</td>
                <td style="width: 100px;">Тип кейса</td>
                <td style="width: 250px;">Дата создания</td>
                <td style="width: 350px;">Автор</td>
                <td>Проект</td>
            </thead>
            {% for testcase in testcases %}
            <tbody>
                <td><input type="checkbox" class="pick" name="testcase_{{ testcase.testcase_id }}" value="{{ testcase.testcase_id }}"></td>
                <td class="clicking" onclick="location.href = '{{ testcase.testcase_id }}/edit/';" style="cursor:pointer; transition: background-color 0.3s ease;">{{ testcase.testcase_id }}</td>
                <td class="name">{{ testcase.name }}</td>
                <td>{{ testcase.priority }}</td>
                <td>{{ testcase.case_type }}</td>
                <td>{{ testcase.creation_date|date:"j M Y" }}</td>
                <td>{{ testcase.id }}</td>
                <td>{{ testcase.project }}</td>
        {% endfor %}
    </div>
    <input type="hidden" id="testset_testcases" name="testset_testcases" value="{{ testset.testcases.all|join:', ' }}">
</form>
<form id="searchForm">
    <input type="text" id="searchInput" style="margin-left:770px;"placeholder="Поиск кейса по названию...">
</form>
<input type="hidden" id="testset_id" value="{{ testset.testset_id }}">
<div style="padding: 20px;background: #eee;z-index: 999;position: fixed;bottom: 5%;right:1%;border:2px solid #ccc;border-radius:5px;">
    <input type="submit"  value="Изменить">
    <a class="close-red" href="/testsets" > Закрыть</a>
</div>

<a class="sort-by"> Сортировать по:</a>
    <select id="id-sort" class="sort-select">
      <option value="">---</option>
      <option value="testcase_id">ID</option>
      <option value="name">Название</option>
      <option value="priority">Приоритет</option>
      <option value="creation_date">Дата создания(возр.)</option>
      <option value="-creation_date">Дата создания(уб.)</option>
      <option value="id">Автор</option>
      <option value="project_id">Проект</option>
    </select>

<script>     
    const testsetId = document.querySelector('#testset_id').value;
    const sortSelects = document.querySelectorAll('.sort-select');

    sortSelects.forEach(select => {
    select.addEventListener('change', event => {
        const selectedOption = event.target.value;
        if (selectedOption) {
            const url = new URL('/testsets/' + testsetId + '/testcase/add/order_by/' + selectedOption + '/', window.location.origin);
        window.location.href = url.toString();
        }
    });
    });

    const checkboxes = document.querySelectorAll('.pick');
    const hiddenInput = document.querySelector('#testset_testcases');

    function updateHiddenInput() {
    const checkedCheckboxes = document.querySelectorAll('.pick:checked');
    const values = Array.from(checkedCheckboxes).map(checkbox => checkbox.value);
    hiddenInput.value = values.join(', ');
    }

    checkboxes.forEach(checkbox => {
    checkbox.addEventListener('change', updateHiddenInput);
    });
</script>

{% endblock lists %}
</body>
</html>

systemart/apps/main/templates/main/edit_bugreport.html
{%load static%}
<!DOCTYPE html>
<html>
<head>
    <title>Редактирование багрепортов</title>
    <link rel="stylesheet" type="text/css" href="{% static '/css/main.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <style>
        .form-row {
            display: flex;
            flex-wrap: wrap;
            margin-right: -15px;
            margin-left: -15px;
        }

        .form-row .col {
            flex: 0 0 auto;
            width: auto;
        }

        .form-row .col-sm-4 {
            flex: 0 0 33.33333%;
            max-width: 33.33333%;
        }

        .form-group {
            margin-bottom: 1rem;
            display: flex;
            align-items: center;
        }

        .form-group-top-label {
            margin-bottom: 1rem;
            display: block;
        }

        label {
            display: inline-block;
            margin-right: 10px;
            margin-bottom: 0;
            width: 90px;
        }

        label.top-label {
            display: block;
            margin-bottom: 0.5rem;
            width: auto;
        }

        textarea {
            resize: vertical;
        }

        #id_name {
            width: 1300px;
            max-width: 1300px;
        }

        #id_description {
            width: 600px;
            height: 300px;
        }

        .verticalLine {
            border-left: 2px solid #ccc;
            margin-left: 70px;
            margin-right: 70px;
            margin-top: -30px;
        }

        input[type="checkbox"] {
            margin-left: 0px;
        }

        label[for="id_bug_file"] {
            margin-right: 50px;
        }
    </style>
</head>
<body style="display: block;">
    <div class="project-form">
        <form method="post" action="{% url 'edit_bugreport' pk=object.pk %}" enctype="multipart/form-data">
            <h2>Редактирование баг репорта</h2>
            <hr size=1 color=#ccc>
            {% csrf_token %}
            <div class="form-group" style="margin-top: -60px; margin-left: -12px; max-width: 1300px;">
                {{ form.name }}
            </div>
            <div class="form-row">
                <div class="col-sm-4">
                    <div class="form-group">
                        <label for="{{ form.priority.id_for_label }}">{{ form.priority.label }}</label>
                        {{ form.priority }}
                    </div>
                </div>
                <div class="col-sm-4">
                    <div class="form-group">
                        <label for="{{ form.project.id_for_label }}">{{ form.project.label }}</label>
                        {{ form.project }}
                    </div>
                </div>
                <div class="col-sm-4">
                    <div class="form-group">
                        <label for="{{ form.status.id_for_label }}">{{ form.status.label }}</label>
                        {{ form.status }}
                    </div>
                </div>
                <div class="col-sm-4">
                    <div class="form-group">
                        <label for="{{ form.id.id_for_label }}">{{ form.id.label }}</label>
                        {{ form.id }}
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="form-group form-group-top-label" style="margin-left:-15px;">
                    <label for="{{ form.testcase.id_for_label }}" class="top-label">{{ form.testcase.label }}</label>
                    {{ form.testcase }}
                </div>
            </div>
            <hr size=2 color=#ccc style="width: 1400px;">
            <div class="form-row">
                <div class="col">
                    <div class="form-group form-group-top-label">
                        <label for="{{ form.description.id_for_label }}" class="top-label">{{ form.description.label }}</label>
                        {{ form.description }}
                    </div>
                    <div class="form-group">
                        <label for="{{ form.bug_file.id_for_label }}">{{ form.bug_file.label }}</label>
                        {{ form.bug_file }}
                    </div>
                </div>
            <input type="submit" value="Сохранить">
            <a class="close-red" href="http://127.0.0.1:8000/bugreports/">Закрыть</a>
        </form>
    </div>
</body>
</html>

systemart/apps/main/templates/main/edit_testset.html
{%load static%}
<!DOCTYPE html>
<html>
<head>
    <title>Редактирование тестового набора</title>
    <link rel="stylesheet" type="text/css" href="{% static '/css/main.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <style>
        .form-row {
            display: flex;
            flex-wrap: wrap;
            margin-right: -15px;
            margin-left: -15px;
        }

        .form-row .col {
            flex: 0 0 auto;
            width: auto;
        }

        .form-row .col-sm-4 {
            flex: 0 0 33.33333%;
            max-width: 33.33333%;
        }

        .form-group {
            margin-bottom: 1rem;
            display: flex;
            align-items: center;
        }

        .form-group-top-label {
            margin-bottom: 1rem;
            display: block;
        }

        label {
            display: inline-block;
            margin-right: 10px;
            margin-bottom: 0;
            width: 90px;
        }

        label.top-label {
            display: block;
            margin-bottom: 0.5rem;
            width: auto;
        }

        textarea {
            resize: vertical;
        }

        #id_testset_name {
            width: 1300px;
            max-width: 1300px;
        }

        #id_description {
            width: 600px;
            height: 300px;
        }

        input[type="checkbox"] {
            margin-left: 0px;
        }

        label[for="id_runtime"] {
            margin-right: 50px;
        }

        .container {
            padding: 10px;
            width: 300px;
            height: 100px;
            overflow-y: auto;
            position: relative;
            border: 1px solid black;
        }


    </style>
</head>
<body style="display: block;">
    <div class="project-form">
        <form method="post" action="{% url 'edit_testset' pk=object.pk %}">
            <h2>Редактирование тестового набора</h2>
            {% csrf_token %}
            <hr size=1 color=#ccc>
            <div class="form-group" style="margin-top: -60px; margin-left: -12px; max-width: 1300px;">
                {{ form.testset_name }}
            </div>
            <div class="form-row">
                <div class="col-sm-4">
                    <div class="form-group">
                        <label for="{{ form.set.id_for_label }}">{{ form.set.label }}</label>
                        {{ form.set }}
                    </div>
                </div>
                <div class="col-sm-4">
                    <div class="form-group">
                        <label for="{{ form.id.id_for_label }}">{{ form.id.label }}</label>
                        {{ form.id }}
                    </div>
                </div>
            </div>
            <div class="form-group" style="height: 100px; margin-left: -12px;">
                <label for="{{ form.testcases.id_for_label }}">{{ form.testcases.label }}</label>
                <div class="container">
                {{ form.testcases }}
                </div>
            </div>
            <input type="submit" value="Сохранить">
            <a class="close-red" href="http://127.0.0.1:8000/testsets/">Закрыть</a>
        </form>
    </div>
</body>
</html>

systemart/apps/main/templates/main/forbidden.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Нет доступа</title>
    <style>
        body {
          text-align: center;
        }
    
        h1 {
          margin-top: 50px;
        }
      </style>
</head>
<body>
    <h1>Доступ запрещен</h1>
</body>
</html>